name: CI/CD → Cloud Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (optional for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: '>= 416.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to authenticate to Artifact Registry
        run: |
          REGION="${{ secrets.GCP_REGION }}"
          echo "Configuring Docker auth for ${REGION}-docker.pkg.dev"
          gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          # ARTIFACT_REGISTRY_REPO secret should be like:
          # asia-south1-docker.pkg.dev/hifive-471520/hifive-repo
          IMAGE="${{ secrets.ARTIFACT_REGISTRY_REPO }}/${{ secrets.CLOUDRUN_SERVICE }}:${{ env.IMAGE_TAG }}"
          echo "Building ${IMAGE}"
          docker build --pull -t "$IMAGE" .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push image to Artifact Registry
        run: |
          echo "Pushing ${IMAGE}"
          docker push "${{ env.IMAGE }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${{ secrets.CLOUDRUN_SERVICE }}" \
            --image "${{ env.IMAGE }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
